name: 'Traffic Lite'
description: 'Preserve GitHub repository traffic data beyond the 14-day limit.'
author: 'Nick Saunders'
branding:
  icon: 'activity'
  color: 'black'
inputs:
  path:
    description: The path to the file where traffic data will be recorded in JSON format
    required: false
    default: '.github/traffic.json'
  repo:
    description: The repository whose traffic data to track, in OWNER/NAME format
    required: true
  token:
    description: The token used to access the GitHub repository traffic API
    required: true
runs:
  using: 'node16'
  main: 'index.js'
